spring.application.name=springpractice
spring.profiles.active=dev

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#auth.validator.type=clerk
#clerk.jwks.url=https://sterling-turkey-6.clerk.accounts.dev/.well-known/jwks.json

logging.level.org.springframework.boot.autoconfigure.security=INFO

# Redis Configuration

# Redis Configuration
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=0
spring.data.redis.ssl.enabled=true
spring.data.redis.timeout=60000ms

# Cache Configuration
app.cache.enabled=${CACHE_ENABLED:true}
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.key-prefix=skillmentor:cache:
spring.cache.redis.use-key-prefix=true