spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.root=INFO

jwt.secret=my-secret-key-must-be-at-least-32-characters-long-for-HS256

spring.security.user.name=admin
spring.security.user.password=admin123
clerk.jwks.url=https://sterling-turkey-6.clerk.accounts.dev/.well-known/jwks.json

auth.validator.type=clerk


